version: "3"
services:
    nifi:
        user: root
        container_name: nifi_container_persistent
        image: 'apache/nifi:latest'
        restart: on-failure
        ports:
            # Admin on host port 8091 maps to container port 8080 on NiFi:
            - '8091:8080'
            # Arbitrary port for sending in data via HTTP POST into NiFi:
            - '65432:65432'
        environment:
            - NIFI_WEB_HTTP_PORT=8080
        healthcheck:
            test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8091/nifi/}"
            interval: "60s"
            timeout: "3s"
            start_period: "5s"
            retries: 5
        volumes:
            - nifi_database_repository:/opt/nifi/nifi-current/database_repository
            - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
            - nifi_content_repository:/opt/nifi/nifi-current/content_repository
            - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
            - nifi_state:/opt/nifi/nifi-current/state
            - nifi_logs:/opt/nifi/nifi-current/logs
            - nifi_conf:/opt/nifi/nifi-current/conf
            # mount host path for reading/writing sample data:
            - ./sample_data:/opt/nifi/nifi-current/sample_data
            # mount host path for reading sample dataflows templates:
            - ./sample_dataflows:/opt/nifi/nifi-current/sample_dataflows
volumes:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_state:
  nifi_logs:
  nifi_conf:

